<a href="https://colab.research.google.com/github/berbir12/ML-Regression/blob/main/Position_Salaries_SVR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR

In [5]:
dataset = pd.read_csv("/content/Position_Salaries.csv")
X = dataset.iloc[:,1:-1].values
Y = dataset.iloc[:, -1].values

In [6]:
Y = Y.reshape(len(Y),1)

In [7]:
scX = StandardScaler()
X = scX.fit_transform(X)
scY = StandardScaler()
Y = scY.fit_transform(Y)

In [8]:
print(X)
print(Y)

[[-1.5666989 ]
 [-1.21854359]
 [-0.87038828]
 [-0.52223297]
 [-0.17407766]
 [ 0.17407766]
 [ 0.52223297]
 [ 0.87038828]
 [ 1.21854359]
 [ 1.5666989 ]]
[[-0.72004253]
 [-0.70243757]
 [-0.66722767]
 [-0.59680786]
 [-0.49117815]
 [-0.35033854]
 [-0.17428902]
 [ 0.17781001]
 [ 0.88200808]
 [ 2.64250325]]


In [9]:
svr = SVR(kernel = "rbf")
svr.fit(X,Y)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [10]:
svr.predict(scX.transform([[6.5]]).reshape(-1,1))

array([-0.27861589])

In [11]:
scY.inverse_transform(svr.predict(scX.transform([[6.5]])).reshape(-1,1))

array([[170370.0204065]])